// src/components/RangeInput.tsx
import { ref, watch } from "jsx";

type VideoProps = {
  value: number,
  min: number,
  max: number,
  step?: number,
  formatter?: (value: number) => unknown,
  "on:keydown"?: (e: KeyboardEvent) => void,
  "on:change": (value: number) => void,
};

export default function RangeInput(props: VideoProps) {
  const [percent, setPercent] = ref(0);
  const [hoverValue, setHoverValue] = ref(0);
  const [labelX, setLabelX] = ref(0);
  const [hoverPercent, setHoverPercent] = ref(0);

  watch(() => setPercent((props.value - props.min) * 100 / (props.max - props.min)));

  function updateHoverValue(this: HTMLDivElement, e: MouseEvent) {
    setLabelX(e.offsetX);
    setHoverValue(e.offsetX / this.clientWidth * (props.max - props.min));
    setHoverPercent(e.offsetX / this.clientWidth * 100);
  }

  return (
    <label class:RangeInput>
      <input
        type="range"
        $min={props.min}
        $max={props.max}
        $step={props.step}
        value={props.value}
        on:input={e => props["on:change"](+e.currentTarget.value)}
        on:mousemove={updateHoverValue}
        on:keydown={props["on:keydown"]}
      />
      <div
        class:progress
        var:progress={`${percent()}%`}
      />
      <label
        $if={!!props.formatter}
        var:x={`${labelX()}px`}
        class:left={hoverPercent() < 8}
        class:right={hoverPercent() > 92}
      >
        <strong>
          {props.formatter!(hoverValue())}
        </strong>
      </label>
    </label>
  );
}

// src/RangeInput.svelte
<script lang="ts">
  type Props = {
    value: number;
    min: number;
    max: number;
    step?: number;
    formatter?: (value: number) => unknown;
    onKeyDown?: (e: KeyboardEvent) => void;
  };

  let {
    value = $bindable(),
    min,
    max,
    step,
    formatter,
    onKeyDown,
  }: Props = $props();

  let percent = $derived(((value - min) * 100) / (max - min));
  let hoverValue = $state(0);
  let labelX = $state(0);
  let hoverPercent = $state(0);

  function setHoverState(this: HTMLDivElement, e: MouseEvent) {
    labelX = e.offsetX;
    hoverValue = (e.offsetX / this.clientWidth) * (max - min);
    hoverPercent = (e.offsetX / this.clientWidth) * 100;
  }
</script>

<label class="range-input">
  <input
    type="range"
    {min}
    {max}
    {step}
    bind:value
    onmousemove={setHoverState}
    onkeydown={onKeyDown}
  />
  <div class="progress" style:--progress={`${percent}%`}></div>
  {#if formatter}
    <output
      style:--x={`${labelX}px`}
      class:left={hoverPercent < 8}
      class:right={hoverPercent > 92}
    >
      <strong>
        {formatter(hoverValue)}
      </strong>
    </output>
  {/if}
</label>
